name: Continuous Integration Python
on:
  push:
    branches:
      - main
      - jenk
  workflow_dispatch:
  
jobs:
  my_first_job:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: jenk

    - name: Show directory
      run: 'pwd'

    - name: List files
      run: 'ls -al'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        python -m unittest discover
